controller_list:
  - name: fake_foundation_controller
    type: $(arg fake_execution_type)
    joints:
      - base_link1
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - link1_link2
initial:  # Define initial robot poses per group
  - group: arm
    pose: home